---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: vault-ingress
spec:
  entryPoints:
    - vault
    - websecure
  routes:
  - match: HostSNI(`*`)
    services:
    - name: vault
      port: 8200
  tls:
    certResolver: letsencrypt
    passthrough: true      