apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: $(AnnotationsCostCenter)-$(AnnotationsEnv)-$(AnnotationsCluster)
# namePrefix: sbx-
resources:
- namespace.yaml
- ../../../base/vault
transformers:
- labels.yaml

generatorOptions:
  disableNameSuffixHash: true

commonAnnotations:
  app.kubernetes.io/version: v0.0.1
  catalog.pbe.io/heritage: pbe.io/catalog/sandbox
  catalog.pbe.io/variant: base
  catalog.pbe.io/cluster: $(AnnotationsCluster)  
  catalog.pbe.io/owner: InfraTeam
  catalog.pbe.io/cost-center: $(AnnotationsCostCenter)
  catalog.pbe.io/department: $(AnnotationsDepartment)
  catalog.pbe.io/environment: $(AnnotationsEnv)
  catalog.pbe.io/region: $(AnnotationsRegion)
  catalog.pbe.io/operating-system: $(AnnotationsOS)
  catalog.pbe.io/encryption: $(AnnotationsEncryption)
  catalog.pbe.io/security-application: $(AnnotationsSecurityApplication)  

configMapGenerator:
- envs:
  - aws-values.env
  name: app-config

# These vars are used for substituing in the parameters from the config map
# into the Profiles custom resource.
configurations:
- params.yaml
vars:
#Vault related parameters
- fieldref:
    fieldPath: data.vault-sa
  name: AppServiceAccountName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
- fieldref:
    fieldPath: data.vault-role
  name: AppServiceAccountRole
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
#Annotations
- fieldref:
    fieldPath: data.cluster
  name: AnnotationsCluster
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
- fieldref:
    fieldPath: data.cost-center
  name: AnnotationsCostCenter
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
- fieldref:
    fieldPath: data.department
  name: AnnotationsDepartment
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
- fieldref:
    fieldPath: data.environment
  name: AnnotationsEnv
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
- fieldref:
    fieldPath: data.region
  name: AnnotationsRegion
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
- fieldref:
    fieldPath: data.operating-system
  name: AnnotationsOS
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
- fieldref:
    fieldPath: data.encryption
  name: AnnotationsEncryption
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
- fieldref:
    fieldPath: data.security-application
  name: AnnotationsSecurityApplication
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
