# apiVersion: v1
# kind: Namespace
# metadata:
#   name: $(AnnotationsCostCenter)-$(AnnotationsEnv)-$(AnnotationsCluster)

---
apiVersion: v1
kind: Namespace
metadata:
  name: $(AnnotationsCostCenter)-$(AnnotationsEnv)-$(AnnotationsCluster)
  labels:
    environment: ${cluster_env:=dev}
    costcenter: "${cluster_cc}"