apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.kubernetes.io/version: v0.0.1
    catalog.pbe.io/cluster: slodev001
    catalog.pbe.io/cost-center: pbe
    catalog.pbe.io/department: Engineering
    catalog.pbe.io/encryption: encrypted
    catalog.pbe.io/environment: sandbox
    catalog.pbe.io/heritage: pbe.io/catalog/sandbox
    catalog.pbe.io/operating-system: os
    catalog.pbe.io/owner: InfraTeam
    catalog.pbe.io/region: us-east-1
    catalog.pbe.io/security-application: NA
    catalog.pbe.io/variant: base
  labels:
    env: pbe-sandbox-slodev001
  name: pbe-sandbox-slodev001
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.kubernetes.io/version: v0.0.1
    catalog.pbe.io/cluster: slodev001
    catalog.pbe.io/cost-center: pbe
    catalog.pbe.io/department: Engineering
    catalog.pbe.io/encryption: encrypted
    catalog.pbe.io/environment: sandbox
    catalog.pbe.io/heritage: pbe.io/catalog/sandbox
    catalog.pbe.io/operating-system: os
    catalog.pbe.io/owner: InfraTeam
    catalog.pbe.io/region: us-east-1
    catalog.pbe.io/security-application: NA
    catalog.pbe.io/variant: base
  labels:
    app: vaultcr
    app.kubernetes.io/component: vault
    app.kubernetes.io/managed-by: vault-operator
    app.kubernetes.io/name: vault-cr-raft
    env: pbe-sandbox-slodev001
  name: vaultcr-sa
  namespace: pbe-sandbox-slodev001
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    app.kubernetes.io/version: v0.0.1
    catalog.pbe.io/cluster: slodev001
    catalog.pbe.io/cost-center: pbe
    catalog.pbe.io/department: Engineering
    catalog.pbe.io/encryption: encrypted
    catalog.pbe.io/environment: sandbox
    catalog.pbe.io/heritage: pbe.io/catalog/sandbox
    catalog.pbe.io/operating-system: os
    catalog.pbe.io/owner: InfraTeam
    catalog.pbe.io/region: us-east-1
    catalog.pbe.io/security-application: NA
    catalog.pbe.io/variant: base
  labels:
    app: vaultcr
    app.kubernetes.io/component: vault
    app.kubernetes.io/managed-by: vault-operator
    app.kubernetes.io/name: vault-cr-raft
    env: pbe-sandbox-slodev001
  name: vaultcr-role
  namespace: pbe-sandbox-slodev001
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    app.kubernetes.io/version: v0.0.1
    catalog.pbe.io/cluster: slodev001
    catalog.pbe.io/cost-center: pbe
    catalog.pbe.io/department: Engineering
    catalog.pbe.io/encryption: encrypted
    catalog.pbe.io/environment: sandbox
    catalog.pbe.io/heritage: pbe.io/catalog/sandbox
    catalog.pbe.io/operating-system: os
    catalog.pbe.io/owner: InfraTeam
    catalog.pbe.io/region: us-east-1
    catalog.pbe.io/security-application: NA
    catalog.pbe.io/variant: base
  labels:
    app: vaultcr
    app.kubernetes.io/component: vault
    app.kubernetes.io/managed-by: vault-operator
    app.kubernetes.io/name: vault-cr-raft
    env: pbe-sandbox-slodev001
  name: vaultcr-role-binding
  namespace: pbe-sandbox-slodev001
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vaultcr-role
subjects:
- kind: ServiceAccount
  name: vaultcr-sa
  namespace: pbe-sandbox-slodev001
---
apiVersion: v1
data:
  cluster: slodev001
  cost-center: pbe
  department: Engineering
  encryption: encrypted
  environment: sandbox
  operating-system: os
  region: us-east-1
  security-application: NA
  vault-sa: vaultcr
kind: ConfigMap
metadata:
  annotations:
    app.kubernetes.io/version: v0.0.1
    catalog.pbe.io/cluster: slodev001
    catalog.pbe.io/cost-center: pbe
    catalog.pbe.io/department: Engineering
    catalog.pbe.io/encryption: encrypted
    catalog.pbe.io/environment: sandbox
    catalog.pbe.io/heritage: pbe.io/catalog/sandbox
    catalog.pbe.io/operating-system: os
    catalog.pbe.io/owner: InfraTeam
    catalog.pbe.io/region: us-east-1
    catalog.pbe.io/security-application: NA
    catalog.pbe.io/variant: base
  labels:
    env: pbe-sandbox-slodev001
  name: vaultcr-config
  namespace: pbe-sandbox-slodev001
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  annotations:
    app.kubernetes.io/version: v0.0.1
    catalog.pbe.io/cluster: slodev001
    catalog.pbe.io/cost-center: pbe
    catalog.pbe.io/department: Engineering
    catalog.pbe.io/encryption: encrypted
    catalog.pbe.io/environment: sandbox
    catalog.pbe.io/heritage: pbe.io/catalog/sandbox
    catalog.pbe.io/operating-system: os
    catalog.pbe.io/owner: InfraTeam
    catalog.pbe.io/region: us-east-1
    catalog.pbe.io/security-application: NA
    catalog.pbe.io/variant: base
  labels:
    app: vaultcr
    app.kubernetes.io/component: vault
    app.kubernetes.io/managed-by: vault-operator
    app.kubernetes.io/name: vault-cr-raft
    env: pbe-sandbox-slodev001
  name: vaultcr
  namespace: pbe-sandbox-slodev001
spec:
  deploy:
  - kapp:
      delete:
        rawOptions:
        - --apply-ignored=true
  fetch:
  - git:
      ref: origin/main
      subPath: instances/apps/vault
      url: https://github.com/milantech-gitops/infra-k8s-system
  serviceAccountName: vaultcr-sa
  template:
  - ytt:
      ignoreUnknownComments: true
