apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-operator
  namespace: flux-system
spec:
  releaseName: vault-operator
  chart:
    spec:
      chart: vault-operator
      version: ">1.0.0"
      sourceRef:
        kind: HelmRepository
        name: banzaicloud-stable
        namespace: infra-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: operator-values
  values:
    replicaCount: 1
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-webhook
  namespace: flux-system
spec:
  releaseName: vault-secrets-webhook
  chart:
    spec:
      chart: vault-secrets-webhook
      version: ">1.0.0"
      sourceRef:
        kind: HelmRepository
        name: banzaicloud-stable
        namespace: infra-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: webhook-values
  values:
    replicaCount: 1