---
# Options for the main traefik service, where the entrypoints traffic comes from.
service:
  enabled: true
  type: LoadBalancer
  # Additional service labels (e.g. for filtering Service by custom labels)
  # spec:
  #   externalTrafficPolicy: Local
    # loadBalancerIP: "1.2.3.4"
    # clusterIP: "2.3.4.5"
# Whether Role Based Access Control objects like roles and rolebindings should be created
rbac:
  enabled: true
# Create an IngressRoute for the dashboard
# ingressRoute:
#   dashboard:
#     enabled: true
# Configure Traefik static configuration
# Additional arguments to be passed at Traefik's binary
# All available options available on https://docs.traefik.io/reference/static-configuration/cli/
## Use curly braces to pass values: `helm install --set="additionalArguments={--providers.kubernetesingress.ingressclass=traefik-internal,--log.level=DEBUG}"`
additionalArguments:
  - --providers.kubernetesingress.ingressclass=traefik-internal
  - --providers.file.filename=/data/traefik-config.yaml
  - --providers.kubernetesIngress=true
  - --entrypoints.websecure.http.tls.certresolver=cloudflare
  - --entrypoints.websecure.http.tls.domains[0].main=milantech.live
  - --entrypoints.websecure.http.tls.domains[0].sans=*.milantech.live
  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
  - --certificatesresolvers.cloudflare.acme.email=staging@milantech.live
  - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
  - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json
ports:
  web:
    redirectTo: websecure
env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        key: email
        name: cloudflare-api-credentials
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        key: apiKey
        name: cloudflare-api-credentials
ingressRoute:
  dashboard:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: traefik
persistence:
  enabled: true
  path: /certs
  size: 128Mi
volumes:
  - mountPath: /data
    name: traefik-config
    type: configMap
# Activate Pilot integration
pilot:
  enabled: true
  token: "ec4d679a-6126-43bb-9f91-2a3959940418"


# ssl:
#   enabled: "true"
#   mtls:
#     optional: "true"
#   generateTLS: "true"

# kubernetes:
#   ingressEndpoint:
#     publishedService: "traefik/traefik"

# metrics:
#   prometheus:
#     enabled: "true"
