apiVersion: v1
kind: Namespace
metadata:
  labels:
    costcenter: pbe
    environment: staging
  name: pbe-xxxx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aaavault-sa
  namespace: pbe-xxxx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aaavault-role
  namespace: pbe-xxxx
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aaavault-role-binding
  namespace: pbe-xxxx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aaavault-role
subjects:
- kind: ServiceAccount
  name: aaavault-sa
  namespace: pbe-xxxx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aaavault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: aaavault-sa
  namespace: pbe-xxxx
