apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-system
resources:
  - banzaicloud.yaml
  - bitnami.yaml
  - jetstack.yaml
  - traefik.yaml
  - kubeview.yaml
  - aecharts.yaml

transformers:
- ../labels.yaml