---
# Default values for vault-secrets-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

debug: true
  # use extra names if you want use the webhook via an ingress or a loadbalancer