#@ load("@ytt:data", "data")
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      version: ">4.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: infra-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/external-dns/values.yaml
  values:
    replicas: #@ data.values.replicas
    aws:
      zoneType: public
    interval: 3m
    policy: upsert-only
    provider: aws
    rbac:
      create: true
      serviceAccountAnnotations:
        eks:
          amazonaws:
            com/role-arn: #@ data.values.role_arn
      serviceAccountName: external-dns
    registry: txt
    txtOwnerId: #@ data.values.txtOwnerId