apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - release.yaml
  - config.yaml
  - traefik-dashboard-secret.yaml
  - traefik-dashboard-ingressroute.yaml
