apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - uninstall-old-release.yaml
  - release.yaml
  - traefik-config.yaml
  # - traefik-dashboard-secret.yaml
  # - traefik-dashboard-ingressroute.yaml

configMapGenerator:
  - name: traefik-values
    files:
      - values.yaml=traefik-values.yaml

configurations:
  - kustomizeconfig.yaml
