---
# Default values for kubeview-values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The namespace where the operator watches for vault CRD objects, if not defined
# all namespaces are watched
installCRDs: true
extraArgs:
  - --cluster-resource-namespace=