apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb
resources:
  - release.yaml

configMapGenerator:
  - name: metallb-config-values
    files:
      - values.yaml=metallb-config.yaml

configurations:
  - kustomizeconfig.yaml