---
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  # See: https://banzaicloud.com/docs/bank-vaults/cli-tool/#example-external-vault-configuration
  # The repository also contains a lot examples in the deploy/ and operator/deploy directories.
  externalConfig:
    auth:
      - type: kubernetes
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: ["default", "vault-secrets-webhook", "vault", "vault-system","pbe-${vault_sa:=vaultcr-sa}"]
            bound_service_account_namespaces: ["default", "vswh", "vault-system","${cluster_cc:=aws}-${cluster_aws_account:=staging}-${cluster_name:=default}"]
            policies: ["allow_secrets", "allow_pki"]
            ttl: 10m
