apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
data:
  cluster-info.json: |
    {
      "cluster": {
        "name": "${cluster}"
      },
      "logs": {
        "region": "${region}"
      }
    }

apiVersion: v1
data:
  data: |
    clusterDefault:
      brokerClass: ChannelBasedBroker
      apiVersion: v1
      kind: ConfigMap
      name: config-br-default-channel
      namespace: knative-eventing
kind: ConfigMap
metadata:
  labels:
    eventing.knative.dev/release: v0.14.2
  name: config-br-defaults
  namespace: knative-eventing

data:
  config: |
    address-pools:
    - addresses:
      - 172.30.0.150-172.30.0.200
      name: default
      protocol: layer2