---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: infra-k8s-system
  namespace: infra-k8s-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: infra-k8s-system
  url: ssh://git@github.com/milantech-gitops/infra-k8s-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infra-k8s-system
  namespace: infra-k8s-system
spec:
  interval: 10m0s
  path: ./cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-k8s-system
  validation: client
