apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
### Disabled Components ###
# - kapp.yaml
### Enabled Components ###
- certmanager.yaml
- kubeview.yaml
- metallb.yaml
- traefik.yaml

transformers:
- ../../../labels.yaml