apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- vars/instance-configmap.yaml
- infrastructure.yaml
- instances.yaml


# generatorOptions:
#   disableNameSuffixHash: true

# Using ConfigMap Generator
configMapGenerator:
- envs:
  - vars/cluster-config-map.env
  name: cluster-config-map
- envs:
  - vars/instance-config-map.env
  name: instance-config-map
  behavior: merge

# These vars are used for substituing in the parameters from the config map
# into the Profiles custom resource.
configurations:
- configs/varreference.yaml

#Cluster related parameters
vars:
- fieldref:
    fieldpath: data.cluster_cloud_provider
  name: CLUSTER_CLOUD_PROVIDER
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-config-map

- fieldref:
    fieldpath: data.cluster_name
  name: CLUSTER_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-config-map

- fieldref:
    fieldpath: data.cluster_aws_account
  name: CLUSTER_AWS_ACCOUNT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-config-map

- fieldref:
    fieldpath: data.cluster_stacks
  name: CLUSTER_STACKS
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-config-map

- fieldref:
    fieldpath: data.cost_center
  name: CLUSTER_COST_CENTER
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-config-map

- fieldref:
    fieldpath: data.department
  name: CLUSTER_DEPARTMENT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-config-map

- fieldref:
    fieldpath: data.region
  name: CLUSTER_REGION
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-config-map

- fieldref:
    fieldpath: data.operating_system
  name: CLUSTER_OS
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-config-map

- fieldref:
    fieldpath: data.encryption
  name: CLUSTER_ENCRYPTION
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-config-map

- fieldref:
    fieldpath: data.security_application
  name: CLUSTER_SEC_APP
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-config-map

#Vault related parameters

- fieldref:
    fieldpath: data.vault_sa
  name: VAULT_SA
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: instance-config-map

- fieldref:
    fieldpath: data.vault_role
  name: VAULT_ROLE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: instance-config-map
