apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeview
spec:
  releaseName: kubeview
  chart:
    spec:
      chart: kubeview
      version: "^0.1.19"
      sourceRef:
        kind: HelmRepository
        name: kubeview
        namespace: infra-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: kubeview-config-values
  values:
    replicaCount: 1