apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: "~>v1.0.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: infra-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: certmanager-config-values
  values:
    replicaCount: 1