apiVersion: v1
kind: ServiceAccount
metadata:
  name: vaultcr-ns-sa
  labels:
    app: vaultcr
  # namespace: vaultcr
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vaultcr-ns-role
  labels:
    app: vaultcr
  # namespace: vaultcr
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vaultcr-ns-role-binding
  labels:
    app: vaultcr
  # namespace: vaultcr
subjects:
- kind: ServiceAccount
  name: vaultcr-ns-sa
  # namespace: vaultcr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vaultcr-ns-role