apiVersion: v1
kind: ConfigMap
metadata:
  name: instance-config-map
  namespace: flux-system
data:
  ui.properties: |
    secret.code.allowed=true
    secret.code.lives=30s
    secret.code.passphrase=UUDDLRLRBABAS