apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure
  prune: true
  validation: client
  postBuild:
    substitute:
      cluster_cloud_provider: '$(CLUSTER_CLOUD_PROVIDER)'
      cluster_name: '$(CLUSTER_NAME)'
      cluster_aws_account: '$(CLUSTER_AWS_ACCOUNT)'
      cluster_cc: '$(CLUSTER_COST_CENTER)'
      cluster_dept: '$(CLUSTER_DEPARTMENT)'
      cluster_region: '$(CLUSTER_REGION)'
      cluster_os: '$(CLUSTER_OS)'
      cluster_encrypt: '$(CLUSTER_ENCRYPTION)'
      cluster_secapp: '$(CLUSTER_SEC_APP)'
      vault_sa: '$(VAULT_SA)'
      vault_role: '$(VAULT_ROLE)'