apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: power-dns
spec:
  releaseName: power-dns
  chart:
    spec:
      chart: powerdns
      version: "^0.1.11"
      sourceRef:
        kind: HelmRepository
        name: aecharts
        namespace: infra-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: powerdns-values
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/power-dns/values.yaml
  values:
    replicas: 1
