apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tenant-sbx
nameSuffix: -sbx
resources:
- namespace.yaml
- ../../bases/rbac
- ../../bases/vaultcr
transformers:
- labels.yaml
