apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  namespace: ${cluster_cc:=aws}-${cluster_aws_account:=staging}-${cluster_name:=default}
fieldSpecs:
  - path: metadata/labels
    create: true