apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ${cluster_name:=default}
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: stacks
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./instances/provider/${cluster_cloud_provider:=aws}/${cluster_aws_account:=sandbox}
  prune: true
  validation: client
  postBuild:
    substitute:
      cluster_cloud_provider: ${cluster_cloud_provider:=aws}
      cluster_name: ${cluster_name:=default}
      cluster_aws_account: ${cluster_aws_account:=sandbox}
      cluster_stacks: ${cluster_stacks:=custom}
      cluster_cc: ${cluster_cc:=infra}
      cluster_dept: ${cluster_dept:=Engineering}
      cluster_region: ${cluster_region:=us-east-1}
      cluster_os: ${cluster_os:=os}
      cluster_encrypt: ${cluster_encrypt:=encrypted}
      cluster_secapp: ${cluster_secapp:=na}
      vault_sa: ${vault_sa:=vaultcr-sa}
      vault_role: ${vault_role:=arn:aws:iam::644712362974:role/node117-playbx-us-west-2}


  ### Reserved for Configmaps ####
  ################################
  # postBuild:
  #   substitute:
  #     cluster_cloud_provider: '$(CLUSTER_CLOUD_PROVIDER)'
  #     cluster_name: '$(CLUSTER_NAME)'
  #     cluster_aws_account: '$(CLUSTER_AWS_ACCOUNT)'
  #     cluster_cc: '$(CLUSTER_COST_CENTER)'
  #     cluster_dept: '$(CLUSTER_DEPARTMENT)'
  #     cluster_region: '$(CLUSTER_REGION)'
  #     cluster_os: '$(CLUSTER_OS)'
  #     cluster_encrypt: '$(CLUSTER_ENCRYPTION)'
  #     cluster_secapp: '$(CLUSTER_SEC_APP)'
  #     vault_sa: '$(VAULT_SA)'
  #     vault_role: '$(VAULT_ROLE)'