apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ${cluster_name:=default}
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: instances
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./instances/provider/${cluster_cloud_provider:=aws}/${cluster_aws_account:=custom}
  prune: true
  validation: client
  postBuild:
    substitute:
      cluster_cloud_provider: ${cluster_cloud_provider:=aws}
      cluster_name: ${cluster_name:=default}
      cluster_aws_account: ${cluster_aws_account:=sandbox}
      cluster_cc: ${cluster_cc:=infra}
      cluster_dept: ${cluster_dept:=Engineering}
      cluster_region: ${cluster_region:=us-east-1}
      cluster_os: ${cluster_os:=os}
      cluster_encrypt: ${cluster_encrypt:=encrypted}
      cluster_secapp: ${cluster_secapp:=na}
      vault_sa: ${vault_sa:=vaultcr-sa}
      vault_role: ${vault_role:=arn:aws:iam::644712362974:role/node117-playbx-us-west-2}