apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
  - sources
  - metallb
  - controllers/vmware-tanzu
  - controllers/traefik
  - certs
  - kubeview
  - vault
  - power-dns
  - external-dns