apiVersion: builtin
kind: LabelTransformer
metadata:
  name: metadataLabelTransformer
labels:
  app.kubernetes.io/name: custom-components
  app.kubernetes.io/instance: infrastructure
  app.kubernetes.io/managed-by: infra-team
  app.kubernetes.io/component: infra
  app.kubernetes.io/part-of: custom
  app.kubernetes.io/version: v0.0.1
fieldSpecs:
- path: metadata/labels
  create: true