apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - release.yaml

configMapGenerator:
  - name: externaldns-values
    files:
      - values.yaml=externaldns-values.yaml

configurations:
  - kustomizeconfig.yaml
