apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      version: ">4.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: infra-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: externaldns-values
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/external-dns/values.yaml
  values:
    replicas: 1
