apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault-system
resources:
  - release.yaml

configMapGenerator:
  - name: vault-dynamic-config-values
    files:
      - values.yaml=vault-dynamic-config.yaml

configurations:
  - kustomizeconfig.yaml

transformers:
  - ../labels.yaml