apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-dynamic-configuration
  namespace: vault-system
spec:
  releaseName: vault-dynamic-configuration-operator
  chart:
    spec:
      chart: vault-dynamic-configuration
      version: "^0.1.1"
      sourceRef:
        kind: HelmRepository
        name: patoarvizu
        namespace: infra-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: vault-dynamic-config-values
  values:
    replicaCount: 1